import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Script src="https://code.iconify.design/2/2.2.0/iconify.min.js"></Script>
        <div className="flex flex-col items-center justify-center max-w-[66%]">
          <h1 className="text-9xl mb-24 font-black">CUNNYLIST</h1>
          <span className="iconify" data-icon="twemoji:loudly-crying-face"></span>
          <p className="text-lg text-center">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde eaque architecto itaque optio alias, molestias illo necessitatibus aut excepturi incidunt. Quasi at id illo cumque nostrum optio consequatur fuga culpa doloribus magnam atque obcaecati possimus neque incidunt dolor aspernatur necessitatibus est modi commodi, similique omnis aliquam quas ducimus. Laboriosam repudiandae, illum ab, doloribus enim ipsam unde officia autem dolorum rem reprehenderit eveniet molestiae sed velit dignissimos suscipit quam. Consequatur delectus quaerat neque doloribus voluptates inventore nulla dolor asperiores perferendis dolorem eaque fuga, at nobis enim ullam dolores! Quae, soluta corrupti? Id dolorem in consequatur minima ea obcaecati corrupti ratione necessitatibus.
          </p>
          {/* Username input */}
          <div className="flex items-center justify-center mt-16 gap-4">
            <input className="bg-white rounded-lg p-2 w-full" type="text" placeholder="Username" />
            <div className="">
              <a href="#" className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-lg">
                Button
              </a>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home